# Change the port
server:
  port: 3000

# Default is already servlet
# You can change it to none if you want an app without a server
spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/customer
    username: faisal
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      show_sql: true
  main:
    web-application-type: servlet